-- schematy
CREATE USER silver NO AUTHENTICATION;
CREATE USER gold   NO AUTHENTICATION;
ALTER USER silver QUOTA UNLIMITED ON DATA;
ALTER USER gold   QUOTA UNLIMITED ON DATA;

-- user (konto deweloperskie)
CREATE USER dev_app IDENTIFIED BY <<haslo>>;
GRANT CREATE SESSION, DWROLE TO dev_app;
ALTER USER dev_app QUOTA UNLIMITED ON DATA;

-- procedury / funkcje / pakiety
GRANT CREATE ANY PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE, EXECUTE ANY PROCEDURE TO dev_app;

-- triggery
GRANT CREATE ANY TRIGGER, ALTER ANY TRIGGER, DROP ANY TRIGGER TO dev_app;

-- typy (przydatne przy pakietach / kolekcjach)
GRANT CREATE ANY TYPE, ALTER ANY TYPE, DROP ANY TYPE, EXECUTE ANY TYPE TO dev_app;

-- materialized views (częste w warstwie gold pod agregaty)
GRANT CREATE ANY MATERIALIZED VIEW, ALTER ANY MATERIALIZED VIEW, DROP ANY MATERIALIZED VIEW TO dev_app;
GRANT GLOBAL QUERY REWRITE TO dev_app;   -- pod query rewrite dla MV

-- synonimy (jeśli będziesz chciał aliasować obiekty między schematami)
GRANT CREATE ANY SYNONYM, DROP ANY SYNONYM TO dev_app;

-- proste joby (DBMS_JOB-style) — zwykle już w DWROLE, ale dokładamy dla pewności
GRANT CREATE JOB TO dev_app;

-- pełny Scheduler (DBMS_SCHEDULER: harmonogramy, programy, okna) — jeśli chcesz zarządzać jobami też w cudzych schematach
GRANT CREATE ANY JOB, MANAGE SCHEDULER TO dev_app;
GRANT EXECUTE ON DBMS_SCHEDULER TO dev_app;


-- SILVER
GRANT SELECT ANY TABLE ON SCHEMA silver TO dev_app;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE ON SCHEMA silver TO dev_app;
GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE ON SCHEMA silver TO dev_app;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE, SELECT ANY SEQUENCE ON SCHEMA silver TO dev_app;
GRANT CREATE ANY INDEX, ALTER ANY INDEX, DROP ANY INDEX ON SCHEMA silver TO dev_app;

-- GOLD
GRANT SELECT ANY TABLE ON SCHEMA gold TO dev_app;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE ON SCHEMA gold TO dev_app;
GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE ON SCHEMA gold TO dev_app;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE, SELECT ANY SEQUENCE ON SCHEMA gold TO dev_app;
GRANT CREATE ANY INDEX, ALTER ANY INDEX, DROP ANY INDEX ON SCHEMA gold TO dev_app;


-- MAINTENANCE
GRANT SELECT ANY TABLE ON SCHEMA maintenance TO dev_app;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE ON SCHEMA maintenance TO dev_app;
GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE ON SCHEMA maintenance TO dev_app;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE, SELECT ANY SEQUENCE ON SCHEMA maintenance TO dev_app;
GRANT CREATE ANY INDEX, ALTER ANY INDEX, DROP ANY INDEX ON SCHEMA maintenance TO dev_app;


