-- =============================================================================
-- silver.def_city
-- -----------------------------------------------------------------------------
-- Słownik SILVER: miasta powiązane ze stacjami kolejowymi. Kolumna station_count
-- (z API) służy kontroli spójności, a is_active oznacza, czy miasto nadal
-- występuje w danych. Klucz sztuczny id, nazwa miasta unikalna.
-- =============================================================================

CREATE TABLE silver.def_city (
    id             NUMBER                    GENERATED BY DEFAULT ON NULL AS IDENTITY,  -- lokalne ID
    name           VARCHAR2(200 CHAR)        NOT NULL,
    station_count  NUMBER,                                              	-- z API, kontrola spójności
    is_active      BOOLEAN                   DEFAULT TRUE NOT NULL,
    loaded_at      TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT pk_dcit_id PRIMARY KEY (id),
    CONSTRAINT uq_dcit_name UNIQUE (name)
);