-- =============================================================================
-- gold.d_route
-- -----------------------------------------------------------------------------
-- Wymiar GOLD: relacja przejazdu okreslona przez stacje poczatkowa i koncowa
-- kursu. Obie kolumny wskazuja na wymiar d_station. Klucz naturalny to para
-- stacji (od -> do), klucz sztuczny id sluzy do łączenia z faktami.
-- =============================================================================

CREATE TABLE gold.d_route (
    id         			NUMBER                    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    from_station_id  	NUMBER                    NOT NULL,   -- stacja początkowa (min order_number) -> d_station
    to_station_id    	NUMBER                    NOT NULL,   -- stacja końcowa (max order_number)  -> d_station
    loaded_at        	TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT pk_droute PRIMARY KEY (id),
    CONSTRAINT uq_droute_from_to UNIQUE (from_station_id, to_station_id)   -- klucz naturalny relacji
);