CREATE TABLE gold.d_train_type (
	id       			NUMBER                    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- kategoria handlowa (Type 1)
    category_code       VARCHAR2(20 CHAR)         NOT NULL,   -- EN, EIC, Os...
    category_name       VARCHAR2(200 CHAR),                   -- "EuroNight"
    speed_category_code VARCHAR2(20 CHAR),
    -- przewoźnik (wersjonowany, Type 2)
    carrier_code        VARCHAR2(20 CHAR)         NOT NULL,
    carrier_name        VARCHAR2(200 CHAR)        NOT NULL,   -- "PKP Intercity"
    -- okres obowiązywania wersji przewoźnika (z silver.def_carrier)
    valid_from          DATE                      NOT NULL,
    valid_to            DATE                      NOT NULL,   -- 2999-12-31 = wersja bieżąca
    loaded_at           TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT pk_dtrtype PRIMARY KEY (train_type_id),
    CONSTRAINT uq_dtrtype_natural UNIQUE (category_code, carrier_code, valid_from)   -- klucz naturalny wersji
);