-- =============================================================================
-- gold.d_train_status
-- -----------------------------------------------------------------------------
-- Wymiar GOLD: slownik statusow kursu pociagu (np. planowy, potwierdzony,
-- odwolany). Kod status_code odpowiada slownikowi z warstwy SILVER; klucz
-- sztuczny id sluzy do laczenia z faktami. Nazwa statusu unikalna per kod.
-- =============================================================================

CREATE TABLE gold.d_train_status (
    id    			NUMBER                    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    status_code  	VARCHAR2(20 CHAR)         NOT NULL,   -- S, P, C, X... (= silver.def_train_status.code)
    status_name  	VARCHAR2(200 CHAR)        NOT NULL,
    loaded_at    	TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT pk_dtrst PRIMARY KEY (id),
    CONSTRAINT uq_dtrst_code UNIQUE (status_code)
);