-- =============================================================================
-- gold.d_disruption_cause
-- -----------------------------------------------------------------------------
-- Wymiar GOLD: slownik przyczyn utrudnien w ruchu pociagow (np. ograniczenie
-- predkosci). Kod cause_code odpowiada slownikowi z warstwy SILVER; klucz
-- sztuczny id sluzy do laczenia z faktami. Nazwa przyczyny unikalna per kod.
-- =============================================================================

CREATE TABLE gold.d_disruption_cause (
    id    		NUMBER                    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cause_code  VARCHAR2(20 CHAR)         NOT NULL,   -- utr_XX (= silver.def_disruption_cause.code)
    cause_name  VARCHAR2(400 CHAR)        NOT NULL,   -- "Ograniczenie prędkości pociągu"
    loaded_at   TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT pk_dcause PRIMARY KEY (id),
    CONSTRAINT uq_dcause_code UNIQUE (cause_code)
);