CREATE TABLE gold.d_disruption_cause (
    id    		NUMBER                    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cause_code  VARCHAR2(20 CHAR)         NOT NULL,   -- utr_XX (= silver.def_disruption_cause.code)
    cause_name  VARCHAR2(400 CHAR)        NOT NULL,   -- "Ograniczenie prędkości pociągu"
    loaded_at   TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT pk_dcause PRIMARY KEY (cause_id),
    CONSTRAINT uq_dcause_code UNIQUE (cause_code)
);