{{
    config(
        materialized='incremental',
        incremental_strategy='append',
        schema='silver'
    )
}}

-- SILVER: schedule_header (pociag danego dnia).
-- "Insert only new": dodajemy tylko klucze, ktorych jeszcze nie ma (NOT EXISTS).
-- Istniejacych nie ruszamy; pusta/powtorzona paczka = 0 wierszy = brak bledu.
-- id = NULL -> Oracle generuje (GENERATED BY DEFAULT ON NULL, migracja V18).

with stg as (
    select * from {{ ref('int_schedule_header') }}
),
dedup as (
    select s.*,
           row_number() over (
               partition by operating_date, schedule_id, order_id, train_order_id
               order by 1
           ) as rn
    from stg s
)
select
    cast(null as number)    as id,
    schedule_id,
    order_id,
    train_order_id,
    operating_date,
    name,
    carrier_code,
    category_code,
    national_number,
    intl_arrival_number,
    intl_departure_number,
    snapshot_ts,
    systimestamp            as loaded_at
from dedup
where rn = 1
{% if is_incremental() %}
  and not exists (
      select 1
      from {{ this }} t
      where t.operating_date = dedup.operating_date
        and t.schedule_id    = dedup.schedule_id
        and t.order_id       = dedup.order_id
        and t.train_order_id = dedup.train_order_id
  )
{% endif %}