name: 'pkp'
version: '1.0.0'
profile: 'pkp'

# Sciezki do plikow projektu
model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  pkp:
    intermediate:
      +materialized: ephemeral  
    silver:
      +materialized: incremental
      +schema: silver