-- =============================================================================
-- maintenance.sql_exec_queue_log
-- -----------------------------------------------------------------------------
-- Tabela logu warstwy utrzymaniowej: historia wykonania poleceń SQL z kolejki
-- DDL (reorganizacje tabel i indeksów). Jeden wiersz na wykonane polecenie -
-- zapisuje treść SQL, czas wykonania, status (DONE / FAILED) oraz komunikat
-- błędu w razie niepowodzenia.
-- =============================================================================

CREATE TABLE maintenance.sql_exec_queue_log (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    executed_at TIMESTAMP WITH TIME ZONE  DEFAULT SYSTIMESTAMP  NOT NULL,
    sql_     CLOB                     NOT NULL,   -- SQL wykonany (kopiowalny do kolejki)
    status      VARCHAR2(10 CHAR)        NOT NULL,   -- DONE / FAILED
    error_msg   VARCHAR2(4000 CHAR),                 -- SQLERRM gdy FAILED, NULL gdy DONE
    CONSTRAINT pk_cmpl_id  PRIMARY KEY (id),
    CONSTRAINT ck_cmpl_st  CHECK (status IN ('DONE','FAILED'))
);

grant select on maintenance.sql_exec_queue_log to DEV_APP;